// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.

using System.Text.Json;
using Duende.IdentityServer.Admin.ApiResources;
using Duende.Storage.EntityAttributeValue;

namespace IdentityServer.UnitTests.Admin;

/// <summary>
/// Documents (rather than assumes) the actual <see cref="System.Text.Json"/> wire shape produced
/// for typed IDs and admin read models. No custom <see cref="System.Text.Json.Serialization.JsonConverter"/>
/// exists for the typed-ID value objects generated by the value-object source generator, so their
/// JSON representation is NOT a bare scalar string the way a raw <see cref="System.Guid"/> serializes:
/// it is a nested object shaped by default reflection-based serialization, and default STJ cannot
/// deserialize it. These tests pin that actual shape and the resulting deserialization failure so
/// the gap is visible and intentional rather than an unnoticed regression.
/// </summary>
public class AdminApiSerializationTests
{
    [Fact]
    public void ApiResourceId_serializes_to_the_default_reflection_shape_not_a_bare_scalar()
    {
        var id = ApiResourceId.New();

        var json = JsonSerializer.Serialize(id);

        // ApiResourceId (like all typed IDs generated via [ValueOf<Guid>]) is a record exposing a
        // single public `Value` property with no [JsonPropertyName] override and no custom
        // converter. Default STJ reflection serialization therefore produces a single-property
        // object using the exact declared member name and casing ("Value"), not a bare GUID string.
        json.ShouldBe($"{{\"Value\":\"{id.Value}\"}}");
    }

    [Fact]
    public void ApiResourceId_deserialization_fails_with_default_reflection_semantics()
    {
        var id = ApiResourceId.New();
        var json = JsonSerializer.Serialize(id);

        // ApiResourceId's only constructor is `private ApiResourceId(Guid value)` -- there is no
        // public parameterless constructor, no accessible parameterized constructor, and no
        // [JsonConstructor] annotation or custom converter. Default STJ reflection-based
        // deserialization has no way to construct an instance, so round-tripping a typed ID through
        // default STJ semantics currently fails with NotSupportedException. This test pins that
        // specific failure so any future behavior change (a JsonConverter being added, STJ changing
        // its exception type, or the constructor visibility changing) produces a real signal.
        var exception = Record.Exception(() => JsonSerializer.Deserialize<ApiResourceId>(json));

        exception.ShouldBeAssignableTo<NotSupportedException>(
            "STJ should throw NotSupportedException for a type with no usable constructor.");
    }

    [Fact]
    public void ApiResourceListItem_round_trip_fails_due_to_nested_typed_id_deserialization()
    {
        var listItem = new ApiResourceListItem
        {
            Id = ApiResourceId.New(),
            Name = "api1",
            DisplayName = "Display",
            Enabled = true,
            Description = "Desc",
            ScopeCount = 3
        };

        var json = JsonSerializer.Serialize(listItem);

        // Serialization succeeds (STJ only needs to read properties, not construct instances), and
        // the nested `Id` property serializes using the same {"Value":"..."} shape pinned above.
        json.ShouldContain("\"Id\":{\"Value\":\"" + listItem.Id.Value + "\"}");

        // Deserialization fails for the same reason as ApiResourceId_deserialization_fails_with_default_reflection_semantics:
        // the nested ApiResourceId has no usable constructor for STJ. This demonstrates that the gap
        // propagates to any read model containing a typed ID.
        var exception = Record.Exception(() => JsonSerializer.Deserialize<ApiResourceListItem>(json));

        exception.ShouldBeAssignableTo<NotSupportedException>(
            "STJ should throw NotSupportedException when a nested typed ID has no usable constructor.");
    }

    [Fact]
    public void ApiResourceConfiguration_round_trips_when_it_contains_no_typed_ids()
    {
        // ApiResourceConfiguration itself carries no typed ID (the parent Configuration model never
        // carries the entity's own Id per the admin API spec), so a full read-model round trip
        // through default STJ semantics succeeds without hitting the typed-ID construction gap.
        var config = new ApiResourceConfiguration
        {
            Name = "api1",
            DisplayName = "Display",
            Description = "Desc",
            Enabled = true,
            ShowInDiscoveryDocument = false,
            RequireResourceIndicator = true,
            UserClaims = ["sub"],
            Scopes = ["scope1"],
            AllowedAccessTokenSigningAlgorithms = ["RS256"]
        };

        var json = JsonSerializer.Serialize(config);
        var deserialized = JsonSerializer.Deserialize<ApiResourceConfiguration>(json);

        deserialized.ShouldNotBeNull();
        deserialized!.Name.ShouldBe(config.Name);
        deserialized.DisplayName.ShouldBe(config.DisplayName);
        deserialized.Description.ShouldBe(config.Description);
        deserialized.Enabled.ShouldBe(config.Enabled);
        deserialized.ShowInDiscoveryDocument.ShouldBe(config.ShowInDiscoveryDocument);
        deserialized.RequireResourceIndicator.ShouldBe(config.RequireResourceIndicator);
        deserialized.UserClaims.ShouldBe(config.UserClaims);
        deserialized.Scopes.ShouldBe(config.Scopes);
        deserialized.AllowedAccessTokenSigningAlgorithms.ShouldBe(config.AllowedAccessTokenSigningAlgorithms);
    }

    [Fact]
    public void AttributeValueCollection_serializes_as_a_json_array_of_code_and_untyped_value_pairs()
    {
        AttributeCode code = "attr1";
        var collection = new AttributeValueCollection();
        collection.Set(code, "v1");

        var json = JsonSerializer.Serialize(collection);

        using var document = JsonDocument.Parse(json);

        // AttributeValueCollection implements IEnumerable<AttributeValue> but has no ICollection<T>
        // surface (only a bespoke Set/TryGet/Remove API), so STJ recognizes it purely as an
        // enumerable and serializes it as a plain JSON array by iterating its enumerator.
        document.RootElement.ValueKind.ShouldBe(JsonValueKind.Array);
        document.RootElement.GetArrayLength().ShouldBe(1);

        var element = document.RootElement[0];

        // Each element's declared type for serialization purposes is the abstract `AttributeValue`
        // base record (the collection's element type), which exposes `Code` (itself a value-object
        // record serialized the same nested way as typed IDs) and `UntypedValue` (declared as
        // `object`, so STJ serializes the boxed runtime value directly rather than hiding it).
        // The derived `AttributeValue<T>.TypedValue` property is NOT visible to the serializer here
        // without additional polymorphism configuration, since the declared element type is the base
        // `AttributeValue`, not the derived `AttributeValue<T>`.
        element.GetProperty("Code").GetProperty("Value").GetString().ShouldBe("attr1");
        element.GetProperty("UntypedValue").GetString().ShouldBe("v1");
    }

    [Fact]
    public void AttributeValueCollection_deserialization_is_not_supported_by_default_reflection_semantics()
    {
        AttributeCode code = "attr1";
        var collection = new AttributeValueCollection();
        collection.Set(code, "v1");
        var json = JsonSerializer.Serialize(collection);

        // AttributeValueCollection has no public parameterless constructor exposed for collection
        // initialization purposes in the way STJ requires (it has multiple constructors, none of
        // which STJ can use to populate elements post-construction, since there is no public
        // `Add(AttributeValue)` method matching the collection-deserialization pattern STJ expects).
        // This test pins the probe result so a future change to STJ's behavior or to the collection's
        // shape produces a real signal.
        var exception = Record.Exception(() => JsonSerializer.Deserialize<AttributeValueCollection>(json));

        exception.ShouldBeAssignableTo<NotSupportedException>(
            "STJ should throw NotSupportedException for a type with no usable constructor.");
    }
}
