// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.

using System.Security.Cryptography.X509Certificates;
using Duende.IdentityServer.Models;

namespace Duende.IdentityServer.Hosts.Shared.Configuration;

public static class SamlServiceProviders
{
    // Path to the MvcSaml SP certificate, relative to the host's working directory.
    // Must match the file generated by following README.md in the MvcSaml project.
    private const string SpCertificatePath = "../../clients/src/MvcSaml/saml-sp.pfx";
    private const string SpCertificatePassword = "changeit";

    public static IEnumerable<SamlServiceProvider> Get() =>
    [
        new SamlServiceProvider
        {
            EntityId = "https://localhost:44350/Saml2",
            DisplayName = "MvcSaml Sample Client",
            Enabled = true,
            // ACS URL follows the Sustainsys.Saml2 convention: <base>/Saml2/Acs
            AssertionConsumerServiceUrls = [new Uri("https://localhost:44350/Saml2/Acs")],
            // SLO URL follows the Sustainsys.Saml2 convention: <base>/Saml2/Logout
            SingleLogoutServiceUrl = new SamlEndpointType
            {
                Location = new Uri("https://localhost:44350/Saml2/Logout"),
                Binding = SamlBinding.HttpRedirect
            },
            // Sign the assertion (not the response envelope) — the Sustainsys default expectation
            SigningBehavior = SamlSigningBehavior.SignAssertion,
            // When the SP certificate is present, require signed AuthnRequests and register the
            // SP's public key so the IdP can validate the signatures.
            RequireSignedAuthnRequests = SpCertificateExists(),
            SigningCertificates = LoadSpSigningCertificates(),
        }
    ];

    private static bool SpCertificateExists() => File.Exists(SpCertificatePath);

    private static ICollection<X509Certificate2> LoadSpSigningCertificates()
    {
        if (!SpCertificateExists())
        {
            return [];
        }

        // For ease during development, we load the public key directly from the SP's certificate file.
        // In a deployed application, you would want to distribute the public key through PKI or
        // another secure channel rather than reading the SP's private key material here.
#pragma warning disable SYSLIB0057
        // Only obsolete in .NET 9+; keeping the older API while we support .NET 8.
        var cert = new X509Certificate2(SpCertificatePath, SpCertificatePassword);
#pragma warning restore SYSLIB0057
        return [cert];
    }
}
