// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using Duende.Storage;
using System.Globalization;
using System.Diagnostics.CodeAnalysis;

namespace Duende.Storage.Internal.Outbox;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<OutboxEventId, global::System.Guid>))]
partial record OutboxEventId : IValueOf<OutboxEventId, global::System.Guid>
{
    // Constructor for controlled creation
    private OutboxEventId(global::System.Guid value) => Value = value;

    public global::System.Guid Value { get; }

    public static OutboxEventId Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid '{nameof(OutboxEventId)}'. {string.Join(" ", errors)}");
        }
        return result;
    }

    public static bool TryCreate(string? s, [NotNullWhen(true)] out OutboxEventId? result)
        => TryCreate(s, out result, out _);

    public static bool TryCreate(string? s, [NotNullWhen(true)] out OutboxEventId? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        if (global::System.Guid.TryParse(s, CultureInfo.InvariantCulture, out var value))
        {
            var instance = new OutboxEventId(value);
            result = instance;
            return true;
        }

        errors = ["The value could not be parsed."];
        return false;
    }

    public static implicit operator OutboxEventId(global::System.Guid value)
    {
        return new OutboxEventId(value);
    }

    public override string ToString() => Value.ToString(null, CultureInfo.InvariantCulture);

    public static OutboxEventId? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static OutboxEventId Load(global::System.Guid value) => new OutboxEventId(value);
}
