// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using Duende.Storage;
using System.Diagnostics.CodeAnalysis;

namespace Duende.Storage.Internal.Outbox;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<OutboxEventName, string>))]
partial record OutboxEventName : IStringValue<OutboxEventName>
{
    // Constructor for controlled creation
    private OutboxEventName(string value) => Value = value;

    public string Value { get; }

    public static OutboxEventName Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid OutboxEventName. {string.Join(" ", errors)}");
        }
        return result;
    }

    public static bool TryCreate(string? s, [NotNullWhen(true)] out OutboxEventName? result)
        => TryCreate(s, out result, out _);

    public static bool TryCreate(string? s, [NotNullWhen(true)] out OutboxEventName? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        var validationErrors = new List<string>();
        if (!Regex().IsMatch(s))
        {
            validationErrors.Add("Must match the required pattern.");
        }
        if (validationErrors.Count > 0)
        {
            errors = validationErrors;
            return false;
        }
        result = new OutboxEventName(s);
        return true;
    }

    public static implicit operator OutboxEventName(string value) => Create(value);

    public override string ToString() => Value;

    public static OutboxEventName? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static OutboxEventName Load(string value) => new OutboxEventName(value);

}
