// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

namespace Duende.UserManagement.Authentication.Passwords;

partial record NonValidatedPassword
{
    // Constructor for controlled creation
    private NonValidatedPassword(string value) => Value = value;

    public static implicit operator NonValidatedPassword(string value) => Create(value);

    public static NonValidatedPassword? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static NonValidatedPassword Load(string value) => new NonValidatedPassword(value);

}
