// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using Duende.UserManagement;
using System.Globalization;

namespace Duende.UserManagement.Scim.Internal;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<ScimETag, global::System.Int32>))]
partial record ScimETag : IValueOf<ScimETag, global::System.Int32>
{
    // Constructor for controlled creation
    private ScimETag(global::System.Int32 value) => Value = value;

    public global::System.Int32 Value { get; }

    public static ScimETag Create(string s)
    {
        if (!TryCreate(s, out var result))
        {
            throw new FormatException($"The value '{s}' is not a valid '{nameof(ScimETag)}'.");
        }
        return result;
    }

    public static implicit operator ScimETag(global::System.Int32 value)
    {
        return new ScimETag(value);
    }

    public override string ToString() => Value.ToString(null, CultureInfo.InvariantCulture);

    public static ScimETag? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static ScimETag Load(global::System.Int32 value) => new ScimETag(value);
}
