// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using Duende.UserManagement;
using System.Globalization;
using System.Diagnostics.CodeAnalysis;

namespace Duende.UserManagement.Admin;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<DataVersion, global::System.Int32>))]
partial record DataVersion : IValueOf<DataVersion, global::System.Int32>
{
    // Constructor for controlled creation
    private DataVersion(global::System.Int32 value) => Value = value;

    public global::System.Int32 Value { get; }

    public static DataVersion Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid '{nameof(DataVersion)}'. {string.Join(" ", errors)}");
        }
        return result;
    }

    public static bool TryCreate(string? s, [NotNullWhen(true)] out DataVersion? result)
        => TryCreate(s, out result, out _);

    public static bool TryCreate(string? s, [NotNullWhen(true)] out DataVersion? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        if (global::System.Int32.TryParse(s, CultureInfo.InvariantCulture, out var value))
        {
            var instance = new DataVersion(value);
            result = instance;
            return true;
        }

        errors = ["The value could not be parsed."];
        return false;
    }

    public static implicit operator DataVersion(global::System.Int32 value)
    {
        return new DataVersion(value);
    }

    public override string ToString() => Value.ToString(null, CultureInfo.InvariantCulture);

    public static DataVersion? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static DataVersion Load(global::System.Int32 value) => new DataVersion(value);
}
