// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using Duende.Storage;
using System.Diagnostics.CodeAnalysis;

namespace Duende.Storage.Pagination;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<ContinuationToken, string>))]
partial record ContinuationToken : IStringValue<ContinuationToken>
{
    // Constructor for controlled creation
    private ContinuationToken(string value) => Value = value;

    public string Value { get; }

    public static ContinuationToken Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid ContinuationToken. {string.Join(" ", errors)}");
        }
        return result;
    }

    public static bool TryCreate(string? s, [NotNullWhen(true)] out ContinuationToken? result)
        => TryCreate(s, out result, out _);

    public static bool TryCreate(string? s, [NotNullWhen(true)] out ContinuationToken? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        result = new ContinuationToken(s);
        return true;
    }

    public static implicit operator ContinuationToken(string value) => Create(value);

    public override string ToString() => Value;

    public static ContinuationToken? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static ContinuationToken Load(string value) => new ContinuationToken(value);

}
