// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using Duende.Storage;
using System.Globalization;
using System.Diagnostics.CodeAnalysis;

namespace Duende.Storage.Pagination;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<OffsetSkip, global::System.Int64>))]
partial record OffsetSkip : IValueOf<OffsetSkip, global::System.Int64>
{
    // Constructor for controlled creation
    private OffsetSkip(global::System.Int64 value) => Value = value;

    public global::System.Int64 Value { get; }

    public static OffsetSkip Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid '{nameof(OffsetSkip)}'. {string.Join(" ", errors)}");
        }
        return result;
    }

    public static bool TryCreate(string? s, [NotNullWhen(true)] out OffsetSkip? result)
        => TryCreate(s, out result, out _);

    public static bool TryCreate(string? s, [NotNullWhen(true)] out OffsetSkip? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        if (global::System.Int64.TryParse(s, CultureInfo.InvariantCulture, out var value))
        {
            if (!TryValidate(value, out var tryValidateErrors))
            {
                errors = tryValidateErrors is { Count: > 0 } ? tryValidateErrors : [$"The value is not a valid '{nameof(OffsetSkip)}'."];
                return false;
            }
            var instance = new OffsetSkip(value);
            result = instance;
            return true;
        }

        errors = ["The value could not be parsed."];
        return false;
    }

    public static implicit operator OffsetSkip(global::System.Int64 value)
    {
        if (!TryValidate(value, out var errors))
        {
            var errorMessage = $"The value '{value}' is not a valid '{nameof(OffsetSkip)}'. {string.Join(" ", errors ?? [])}";
            throw new FormatException(errorMessage);
        }
        return new OffsetSkip(value);
    }

    public override string ToString() => Value.ToString(null, CultureInfo.InvariantCulture);

    public static OffsetSkip? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static OffsetSkip Load(global::System.Int64 value) => new OffsetSkip(value);
}
