// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using Duende.Storage;
using System.Globalization;
using System.Diagnostics.CodeAnalysis;

namespace Duende.Storage.Pagination;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<PageNumber, global::System.Int32>))]
partial record PageNumber : IValueOf<PageNumber, global::System.Int32>
{
    // Constructor for controlled creation
    private PageNumber(global::System.Int32 value) => Value = value;

    public global::System.Int32 Value { get; }

    public static PageNumber Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid '{nameof(PageNumber)}'. {string.Join(" ", errors)}");
        }
        return result;
    }

    public static bool TryCreate(string? s, [NotNullWhen(true)] out PageNumber? result)
        => TryCreate(s, out result, out _);

    public static bool TryCreate(string? s, [NotNullWhen(true)] out PageNumber? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        if (global::System.Int32.TryParse(s, CultureInfo.InvariantCulture, out var value))
        {
            if (!TryValidate(value, out var tryValidateErrors))
            {
                errors = tryValidateErrors is { Count: > 0 } ? tryValidateErrors : [$"The value is not a valid '{nameof(PageNumber)}'."];
                return false;
            }
            var instance = new PageNumber(value);
            result = instance;
            return true;
        }

        errors = ["The value could not be parsed."];
        return false;
    }

    public static implicit operator PageNumber(global::System.Int32 value)
    {
        if (!TryValidate(value, out var errors))
        {
            var errorMessage = $"The value '{value}' is not a valid '{nameof(PageNumber)}'. {string.Join(" ", errors ?? [])}";
            throw new FormatException(errorMessage);
        }
        return new PageNumber(value);
    }

    public override string ToString() => Value.ToString(null, CultureInfo.InvariantCulture);

    public static PageNumber? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static PageNumber Load(global::System.Int32 value) => new PageNumber(value);
}
