// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace Duende.UserManagement;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<UserSubjectId, string>))]
partial record UserSubjectId : IStringValue<UserSubjectId>
{
    // Constructor for controlled creation
    private UserSubjectId(string value) => Value = value;

    public string Value { get; }

    public static UserSubjectId Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid UserSubjectId. {string.Join(" ", errors)}");
        }
        return result;
    }

    public static bool TryCreate(string? s, [NotNullWhen(true)] out UserSubjectId? result)
        => TryCreate(s, out result, out _);

    public static bool TryCreate(string? s, [NotNullWhen(true)] out UserSubjectId? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        var validationErrors = new List<string>();
        if (s.Length > MaxLength)
        {
            validationErrors.Add($"Must not exceed {MaxLength} characters.");
        }
        if (validationErrors.Count > 0)
        {
            errors = validationErrors;
            return false;
        }
        result = new UserSubjectId(s);
        return true;
    }

    public static implicit operator UserSubjectId(string value) => Create(value);

    public override string ToString() => Value;

    public static UserSubjectId? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static UserSubjectId Load(string value) => new UserSubjectId(value);

}
