<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Duende.Spaces</AssemblyName>
    <RootNamespace>Duende.Spaces</RootNamespace>
    <NoWarn>$(NoWarn);CA1812</NoWarn> <!-- never instantiated internal class-->
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Duende.Storage" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
  </ItemGroup>

</Project>
