// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace Duende.Storage;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<DataCategoryName, string>))]
partial record DataCategoryName : IStringValue<DataCategoryName>
{
    // Constructor for controlled creation
    private DataCategoryName(string value) => Value = value;

    /// <summary>Gets the underlying string value of this <see cref="DataCategoryName"/>.</summary>
    public string Value { get; }

    /// <summary>Creates a <see cref="DataCategoryName" /> from the specified string value.</summary>
    /// <param name="s">The string value.</param>
    /// <returns>A new <see cref="DataCategoryName" /> instance.</returns>
    /// <exception cref="FormatException">Thrown when <paramref name="s" /> is not a valid <see cref="DataCategoryName" />.</exception>
    public static DataCategoryName Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid DataCategoryName. {string.Join(" ", errors)}");
        }
        return result;
    }

    /// <summary>Tries to create a <see cref="DataCategoryName" /> from the specified string value.</summary>
    /// <param name="s">The string value.</param>
    /// <param name="result">When this method returns <see langword="true" />, contains the created <see cref="DataCategoryName" />.</param>
    /// <returns><see langword="true" /> if the value is valid; otherwise, <see langword="false" />.</returns>
    public static bool TryCreate(string? s, [NotNullWhen(true)] out DataCategoryName? result)
        => TryCreate(s, out result, out _);

    /// <summary>Tries to create a <see cref="DataCategoryName" /> from the specified string value.</summary>
    /// <param name="s">The string value.</param>
    /// <param name="result">When this method returns <see langword="true" />, contains the created <see cref="DataCategoryName" />.</param>
    /// <param name="errors">When this method returns <see langword="false" />, contains the validation errors.</param>
    /// <returns><see langword="true" /> if the value is valid; otherwise, <see langword="false" />.</returns>
    public static bool TryCreate(string? s, [NotNullWhen(true)] out DataCategoryName? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        result = new DataCategoryName(s);
        return true;
    }

    /// <summary>Implicitly converts a <see cref="string"/> to a <see cref="DataCategoryName"/>.</summary>
    /// <param name="value">The string value to convert.</param>
    /// <returns>A new <see cref="DataCategoryName"/> instance.</returns>
    public static implicit operator DataCategoryName(string value) => Create(value);

    /// <inheritdoc />
    public override string ToString() => Value;

    /// <summary>Creates a new <see cref="DataCategoryName"/> from the specified string value, or returns <see langword="null"/> if the input is null or empty.</summary>
    /// <param name="input">The string value to create the <see cref="DataCategoryName"/> from.</param>
    /// <returns>A new <see cref="DataCategoryName"/> instance, or <see langword="null"/> if <paramref name="input"/> is null or empty.</returns>
    public static DataCategoryName? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static DataCategoryName Load(string value) => new DataCategoryName(value);

}
