// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using System.Globalization;
using System.Diagnostics.CodeAnalysis;

namespace Duende.Storage;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<UuidV7, global::System.Guid>))]
partial record UuidV7 : IValueOf<UuidV7, global::System.Guid>
{
    // Constructor for controlled creation
    private UuidV7(global::System.Guid value) => Value = value;

    public global::System.Guid Value { get; }

    public static UuidV7 Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid '{nameof(UuidV7)}'. {string.Join(" ", errors)}");
        }
        return result;
    }

    public static bool TryCreate(string? s, [NotNullWhen(true)] out UuidV7? result)
        => TryCreate(s, out result, out _);

    public static bool TryCreate(string? s, [NotNullWhen(true)] out UuidV7? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        if (global::System.Guid.TryParse(s, CultureInfo.InvariantCulture, out var value))
        {
            if (!TryValidate(value, out var tryValidateErrors))
            {
                errors = tryValidateErrors is { Count: > 0 } ? tryValidateErrors : [$"The value is not a valid '{nameof(UuidV7)}'."];
                return false;
            }
            var instance = new UuidV7(value);
            result = instance;
            return true;
        }

        errors = ["The value could not be parsed."];
        return false;
    }

    public static implicit operator UuidV7(global::System.Guid value)
    {
        if (!TryValidate(value, out var errors))
        {
            var errorMessage = $"The value '{value}' is not a valid '{nameof(UuidV7)}'. {string.Join(" ", errors ?? [])}";
            throw new FormatException(errorMessage);
        }
        return new UuidV7(value);
    }

    public override string ToString() => Value.ToString(null, CultureInfo.InvariantCulture);

    public static UuidV7? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static UuidV7 Load(global::System.Guid value) => new UuidV7(value);
}
