// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using Duende.UserManagement;
using System.Diagnostics.CodeAnalysis;

namespace Duende.UserManagement.Membership;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<RoleId, string>))]
partial record RoleId : IStringValue<RoleId>
{
    // Constructor for controlled creation
    private RoleId(string value) => Value = value;

    public string Value { get; }

    public static RoleId Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid RoleId. {string.Join(" ", errors)}");
        }
        return result;
    }

    public static bool TryCreate(string? s, [NotNullWhen(true)] out RoleId? result)
        => TryCreate(s, out result, out _);

    public static bool TryCreate(string? s, [NotNullWhen(true)] out RoleId? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        var validationErrors = new List<string>();
        if (s.Length > MaxLength)
        {
            validationErrors.Add($"Must not exceed {MaxLength} characters.");
        }
        if (!Regex().IsMatch(s))
        {
            validationErrors.Add("Must match the required pattern.");
        }
        if (validationErrors.Count > 0)
        {
            errors = validationErrors;
            return false;
        }
        result = new RoleId(s);
        return true;
    }

    public static implicit operator RoleId(string value) => Create(value);

    public override string ToString() => Value;

    public static RoleId? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static RoleId Load(string value) => new RoleId(value);

}
