// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using Duende.UserManagement;
using System.Diagnostics.CodeAnalysis;

namespace Duende.UserManagement.Membership;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<RoleDescription, string>))]
partial record RoleDescription : IStringValue<RoleDescription>
{
    // Constructor for controlled creation
    private RoleDescription(string value) => Value = value;

    public static RoleDescription Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid RoleDescription. {string.Join(" ", errors)}");
        }
        return result;
    }

    public static bool TryCreate(string? s, [NotNullWhen(true)] out RoleDescription? result)
        => TryCreate(s, out result, out _);

    public static bool TryCreate(string? s, [NotNullWhen(true)] out RoleDescription? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        s = Normalize(s);
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["Value is empty after normalization."];
            return false;
        }
        var validationErrors = new List<string>();
        if (s.Length > MaxLength)
        {
            validationErrors.Add($"Must not exceed {MaxLength} characters.");
        }
        if (validationErrors.Count > 0)
        {
            errors = validationErrors;
            return false;
        }
        result = new RoleDescription(s);
        return true;
    }

    public static implicit operator RoleDescription(string value) => Create(value);

    public override string ToString() => Value;

    public static RoleDescription? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

}
