// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.

namespace Duende.ValueObjectsGenerator;

/// <summary>
/// Generates the per-project infrastructure files: IValueOf.g.cs,
/// ValueOfTypeConverter.g.cs, and CharsetExtensions.g.cs.
/// The content is identical to what the Roslyn source generator (Setup.cs) produced.
/// </summary>
internal static class InfrastructureCodeGenerator
{
    internal static string GetInterfaceSource(string rootNamespace) => NormalizeLineEndings($$"""
        // <auto-generated by="ValueObjectsGenerator"/>
        // Copyright (c) Duende Software. All rights reserved.
        // See LICENSE in the project root for license information.
        #nullable enable

        using System.Diagnostics.CodeAnalysis;

        namespace {{rootNamespace}};

        /// <summary>
        /// Provides type-safe access to the underlying value of a value object.
        /// </summary>
        /// <typeparam name="T">The type of the underlying value.</typeparam>
        internal interface IValueOf<T>
        {
            /// <summary>
            /// Gets the underlying value.
            /// </summary>
            T Value { get; }
        }

        /// <summary>
        /// Provides type-safe access to the underlying value of a value object,
        /// along with creation capabilities.
        /// </summary>
        /// <typeparam name="TSelf">The value object type itself.</typeparam>
        /// <typeparam name="T">The type of the underlying value.</typeparam>
        internal interface IValueOf<TSelf, T> : IValueOf<T> where TSelf : IValueOf<TSelf, T>
        {
            /// <summary>
            /// Creates a value object from a string representation.
            /// </summary>
            static abstract TSelf Create(string s);

            /// <summary>
            /// Tries to create a value object from a string representation.
            /// </summary>
            static abstract bool TryCreate(string? s, [NotNullWhen(true)] out TSelf? result);
        }

        internal interface IStringValue<TSelf> : IValueOf<TSelf, string> where TSelf : IStringValue<TSelf>
        {
        }

        """);

    internal static string GetCharSetsSource(string rootNamespace) => NormalizeLineEndings($$"""
        // <auto-generated by="ValueObjectsGenerator"/>
        // Copyright (c) Duende Software. All rights reserved.
        // See LICENSE in the project root for license information.
        #nullable enable

        using System;
        using System.Text;

        namespace {{rootNamespace}};

        /// <summary>
        /// Extension methods for CharSet validation
        /// </summary>
        internal static class CharSetExtensions
        {
            /// <summary>
            /// Defines the set of symbols for the 'Symbols' flag.
            /// </summary>
            private const string SymbolSet = "!@#$%^&*()_+-=[]{}|;:',.<>/?";

            /// <summary>
            /// Gets the combined string of all allowed characters for a given CharSet.
            /// </summary>
            internal static string GetAllowedCharacters(this CharSet charset)
            {
                var sb = new StringBuilder();

                if (charset.HasFlag(CharSet.LowercaseLatin))
                {
                    sb.Append("abcdefghijklmnopqrstuvwxyz");
                }
                if (charset.HasFlag(CharSet.UppercaseLatin))
                {
                    sb.Append("ABCDEFGHIJKLMNOPQRSTUVWXYZ");
                }
                if (charset.HasFlag(CharSet.Digits))
                {
                    sb.Append("0123456789");
                }
                if (charset.HasFlag(CharSet.Symbols))
                {
                    sb.Append(SymbolSet);
                }

                return sb.ToString();
            }

            /// <summary>
            /// Checks if a string contains ONLY characters defined by the CharSet.
            /// </summary>
            /// <param name="charset">The charset to validate against.</param>
            /// <param name="input">The string to check.</param>
            /// <returns>True if the string is null, empty, or contains only allowed characters. False otherwise.</returns>
            internal static bool IsMatch(this CharSet charset, string input)
            {
                // An empty or null string contains no *invalid* characters.
                if (string.IsNullOrEmpty(input))
                {
                    return true;
                }

                // Cache the flags for quick lookups inside the loop
                bool allowLower = charset.HasFlag(CharSet.LowercaseLatin);
                bool allowUpper = charset.HasFlag(CharSet.UppercaseLatin);
                bool allowDigits = charset.HasFlag(CharSet.Digits);
                bool allowSymbols = charset.HasFlag(CharSet.Symbols);

                foreach (char c in input)
                {
                    // We use a series of 'continue' statements.
                    // If any condition is met, the character is valid, and we check the next.

                    // Using BCL methods is faster than c >= 'a' && c <= 'z'
                    if (allowLower && char.IsAsciiLetterLower(c))
                    {
                        continue;
                    }
                    if (allowUpper && char.IsAsciiLetterUpper(c))
                    {
                        continue;
                    }
                    if (allowDigits && char.IsAsciiDigit(c))
                    {
                        continue;
                    }

                    // For symbols, checking against the string is the clearest way
                    if (allowSymbols && SymbolSet.Contains(c))
                    {
                        continue;
                    }

                    // If we get here, the character 'c' did not match any
                    // allowed set, so the string is not a match.
                    return false;
                }

                // If the loop finishes, all characters were valid.
                return true;
            }
        }

        """);

    internal static string GetTypeConverterSource(string rootNamespace) => NormalizeLineEndings($$"""
        // <auto-generated by="ValueObjectsGenerator"/>
        // Copyright (c) Duende Software. All rights reserved.
        // See LICENSE in the project root for license information.
        #nullable enable

        using System;
        using System.ComponentModel;
        using System.Globalization;

        namespace {{rootNamespace}};

        /// <summary>
        /// Generic type converter for value objects.
        /// Enables ASP.NET Core model binding and IConfiguration support.
        /// </summary>
        internal class ValueOfTypeConverter<TValue, TType> : TypeConverter where TValue : IValueOf<TValue, TType>
        {
            public override bool CanConvertFrom(ITypeDescriptorContext? context, Type sourceType)
            {
                return sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);
            }

            public override object? ConvertFrom(ITypeDescriptorContext? context, CultureInfo? culture, object value)
            {
                if (value is string stringValue)
                {
                    if (TValue.TryCreate(stringValue, out var result))
                    {
                        return result;
                    }
                    throw new FormatException($"'{stringValue}' is not a valid {typeof(TValue).Name}.");
                }
                return base.ConvertFrom(context, culture!, value);
            }

            public override bool CanConvertTo(ITypeDescriptorContext? context, Type? destinationType)
            {
                return destinationType == typeof(string) || base.CanConvertTo(context, destinationType);
            }

            public override object? ConvertTo(ITypeDescriptorContext? context, CultureInfo? culture, object? value, Type destinationType)
            {
                if (destinationType == typeof(string) && value is TValue typedValue)
                {
                    return (typedValue.Value is IFormattable formattable)
                        ? formattable.ToString(null, CultureInfo.InvariantCulture)
                        : typedValue.Value?.ToString();
                }
                return base.ConvertTo(context, culture, value, destinationType);
            }
        }

        """);

    private static string NormalizeLineEndings(string source) => source.Replace("\r\n", "\n", StringComparison.Ordinal);
}
