// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using Duende.IdentityServer;
using System.Diagnostics.CodeAnalysis;

namespace Duende.IdentityServer.Admin.SamlServiceProviders;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<SamlServiceProviderId, global::System.Guid>))]
partial record SamlServiceProviderId : IValueOf<SamlServiceProviderId, global::System.Guid>
{
    // Constructor for controlled creation
    /// <summary>Initializes a new instance of <see cref="SamlServiceProviderId"/> with the specified value.</summary>
    /// <param name="value">The underlying value.</param>
    private SamlServiceProviderId(global::System.Guid value) => Value = value;

    /// <summary>Gets the underlying value of this <see cref="SamlServiceProviderId"/>.</summary>
    public global::System.Guid Value { get; }

    /// <summary>Creates a <see cref="SamlServiceProviderId"/> from the specified string, throwing if the value is invalid.</summary>
    /// <param name="s">The string value to create the <see cref="SamlServiceProviderId"/> from.</param>
    /// <returns>A new <see cref="SamlServiceProviderId"/> parsed from <paramref name="s"/>.</returns>
    /// <exception cref="global::System.FormatException">Thrown when <paramref name="s"/> is not a valid value.</exception>
    public static SamlServiceProviderId Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid '{nameof(SamlServiceProviderId)}'. {string.Join(" ", errors)}");
        }
        return result;
    }

    /// <summary>Tries to create a <see cref="SamlServiceProviderId"/> from the specified string.</summary>
    /// <param name="s">The string value to parse.</param>
    /// <param name="result">When this method returns <see langword="true"/>, contains the created <see cref="SamlServiceProviderId"/>; otherwise <see langword="null"/>.</param>
    /// <returns><see langword="true"/> if <paramref name="s"/> is a valid value; otherwise <see langword="false"/>.</returns>
    public static bool TryCreate(string? s, [NotNullWhen(true)] out SamlServiceProviderId? result)
        => TryCreate(s, out result, out _);

    /// <summary>Tries to create a <see cref="SamlServiceProviderId"/> from the specified string, returning validation errors on failure.</summary>
    /// <param name="s">The string value to parse.</param>
    /// <param name="result">When this method returns <see langword="true"/>, contains the created <see cref="SamlServiceProviderId"/>; otherwise <see langword="null"/>.</param>
    /// <param name="errors">When this method returns <see langword="false"/>, contains the validation error messages; otherwise <see langword="null"/>.</param>
    /// <returns><see langword="true"/> if <paramref name="s"/> is a valid value; otherwise <see langword="false"/>.</returns>
    public static bool TryCreate(string? s, [NotNullWhen(true)] out SamlServiceProviderId? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        if (global::System.Guid.TryParse(s, global::System.Globalization.CultureInfo.InvariantCulture, out var value))
        {
            if (!TryValidate(value, out var tryValidateErrors))
            {
                errors = tryValidateErrors is { Count: > 0 } ? tryValidateErrors : [$"The value is not a valid '{nameof(SamlServiceProviderId)}'."];
                return false;
            }
            var instance = new SamlServiceProviderId(value);
            result = instance;
            return true;
        }

        errors = ["The value could not be parsed."];
        return false;
    }

    /// <summary>Implicitly converts a <c>global::System.Guid</c> to a <see cref="SamlServiceProviderId"/>.</summary>
    /// <param name="value">The value to convert.</param>
    /// <returns>A new <see cref="SamlServiceProviderId"/> wrapping <paramref name="value"/>.</returns>
    /// <exception cref="global::System.FormatException">Thrown when <paramref name="value"/> fails validation.</exception>
    public static implicit operator SamlServiceProviderId(global::System.Guid value)
    {
        if (!TryValidate(value, out var errors))
        {
            var errorMessage = $"The value '{value}' is not a valid '{nameof(SamlServiceProviderId)}'. {string.Join(" ", errors ?? [])}";
            throw new FormatException(errorMessage);
        }
        return new SamlServiceProviderId(value);
    }

    /// <inheritdoc />
    public override string ToString() => Value.ToString(null, global::System.Globalization.CultureInfo.InvariantCulture);

    /// <summary>Creates a <see cref="SamlServiceProviderId"/> from the specified string, or returns <see langword="null"/> if the input is null or empty.</summary>
    /// <param name="input">The string value to parse, or <see langword="null"/>.</param>
    /// <returns>A <see cref="SamlServiceProviderId"/> if <paramref name="input"/> is non-empty; otherwise <see langword="null"/>.</returns>
    public static SamlServiceProviderId? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    /// <summary>Loads a <see cref="SamlServiceProviderId"/> directly from a stored value, bypassing validation. For infrastructure use only.</summary>
    /// <param name="value">The raw stored value.</param>
    /// <returns>A <see cref="SamlServiceProviderId"/> wrapping <paramref name="value"/>.</returns>
    internal static SamlServiceProviderId Load(global::System.Guid value) => new SamlServiceProviderId(value);
}
