name: "CI"

on:
  push:
    branches:
      - main
      - releases/is/**
    tags:
      - 'is/*.*.*'
    paths: 
    - 'identity-server/**'

  pull_request:
    paths: 
    - 'identity-server/**'
env:
  DOTNET_NOLOGO: true

permissions:
  contents: read
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    defaults:
      run:
        working-directory: identity-server
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
    
    - name: Setup dotnet (main)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            8.0.x
            9.0.x
    
    - run: dotnet --info
    
    - if: contains(matrix.runs-on, 'macOS') || contains(matrix.runs-on, 'ubuntu')
      run: ./build.sh
    - if: matrix.runs-on == 'windows-latest' && github.ref != 'refs/heads/main' && !contains(github.ref, 'refs/tags/')
      run: ./build.ps1
    - if: (matrix.runs-on == 'windows-latest') && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
      env:
        SignClientSecret: ${{ secrets.SIGNCLIENTSECRET }}
      run: |
        ./build.ps1 sign
        dotnet nuget push .\identity-server\artifacts\*.nupkg -s https://www.myget.org/F/duende_identityserver/api/v2/package -k ${{ secrets.MYGET }}
