// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using Duende.Storage;
using System.Diagnostics.CodeAnalysis;

namespace Duende.Storage.EntityAttributeValue;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<AttributeCode, string>))]
partial record AttributeCode : IStringValue<AttributeCode>
{
    // Constructor for controlled creation
    private AttributeCode(string value) => Value = value;

    public string Value { get; }

    public static AttributeCode Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid AttributeCode. {string.Join(" ", errors)}");
        }
        return result;
    }

    public static bool TryCreate(string? s, [NotNullWhen(true)] out AttributeCode? result)
        => TryCreate(s, out result, out _);

    public static bool TryCreate(string? s, [NotNullWhen(true)] out AttributeCode? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        s = Normalize(s);
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["Value is empty after normalization."];
            return false;
        }
        var validationErrors = new List<string>();
        if (s.Length > MaxLength)
        {
            validationErrors.Add($"Must not exceed {MaxLength} characters.");
        }
        if (!TryValidate(s, out var tryValidateErrors))
        {
            if (tryValidateErrors is { Count: > 0 })
            {
                validationErrors.AddRange(tryValidateErrors);
            }
            else
            {
                validationErrors.Add($"The value '{s}' is not valid.");
            }
        }
        if (validationErrors.Count > 0)
        {
            errors = validationErrors;
            return false;
        }
        result = new AttributeCode(s);
        return true;
    }

    public static implicit operator AttributeCode(string value) => Create(value);

    public override string ToString() => Value;

    public static AttributeCode? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static AttributeCode Load(string value) => new AttributeCode(value);

    public virtual bool Equals(AttributeCode? other) =>
        other is not null && Comparer.Equals(Value, other.Value);

    public override int GetHashCode() =>
        Value is null ? 0 : Comparer.GetHashCode(Value);

}
