// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using Duende.Storage;
using System.Diagnostics.CodeAnalysis;

namespace Duende.Storage.EntityAttributeValue;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<AttributeGroupCode, string>))]
partial record AttributeGroupCode : IStringValue<AttributeGroupCode>
{
    // Constructor for controlled creation
    private AttributeGroupCode(string value) => Value = value;

    public string Value { get; }

    public static AttributeGroupCode Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid AttributeGroupCode. {string.Join(" ", errors)}");
        }
        return result;
    }

    public static bool TryCreate(string? s, [NotNullWhen(true)] out AttributeGroupCode? result)
        => TryCreate(s, out result, out _);

    public static bool TryCreate(string? s, [NotNullWhen(true)] out AttributeGroupCode? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        s = Normalize(s);
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["Value is empty after normalization."];
            return false;
        }
        var validationErrors = new List<string>();
        if (s.Length > MaxLength)
        {
            validationErrors.Add($"Must not exceed {MaxLength} characters.");
        }
        if (!Regex().IsMatch(s))
        {
            validationErrors.Add("Must match the required pattern.");
        }
        if (validationErrors.Count > 0)
        {
            errors = validationErrors;
            return false;
        }
        result = new AttributeGroupCode(s);
        return true;
    }

    public static implicit operator AttributeGroupCode(string value) => Create(value);

    public override string ToString() => Value;

    public static AttributeGroupCode? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static AttributeGroupCode Load(string value) => new AttributeGroupCode(value);

    public virtual bool Equals(AttributeGroupCode? other) =>
        other is not null && Comparer.Equals(Value, other.Value);

    public override int GetHashCode() =>
        Value is null ? 0 : Comparer.GetHashCode(Value);

}
